# This is a basic workflow to help you get started with Actions

name: BalenaCloud Push

# Controls when the action will run. 
on:
  # Triggers the workflow on schedule
  schedule:
    - cron: "0 9 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "balena-push"
  balena-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: amingilani/push-to-balenacloud@v1.0.1
        with:
          api-token: ${{secrets.BALENA_API_TOKEN}}
          application-name: ${{secrets.BALENA_APPLICATION_NAME}}
